spring:
  application:
    name: rc-ops-resource
  profiles:
    # 环境配置
    active: dev
  cloud:
    nacos:
#      config:
#        server-addr: 125.124.110.195:31001
#        username: nacos
#        password: nacos
#        file-extension: yaml
#        enabled: true
#        namespace: 4cca4105-2349-43bd-9690-58943921372f
      discovery:
        server-addr: 127.0.0.1:8848
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB
#  boot:
#    admin:
#      client:
#        url: http://localhost:5001
#        username: admin
#        password: admin
#        instance:
#          prefer-ip: true
rc:
  info:
    version: 1.0.0
    base-package: com.rc.cloud



#management:
#  health:
#    redis:
#      enabled: false
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: "*"

