---
apiVersion: v1
kind: Namespace
metadata:
  name: PROJECT_NS
---
apiVersion: v1
kind: Service
metadata:
  name: APP_NAME
  labels:
    app: ci-cd-demo
spec:
  type: NodePort
  ports:
    - name: ci-cd-demo
      port: 8080
      protocol: TCP
      nodePort: 30080
  selector:
    app: ci-cd-demo

---
apiVersion: apps/v1
kind: Deployment #对象类型
metadata:
  name: APP_NAME #名称
  labels:
    app: ci-cd-demo #标注
spec:
  replicas: 3 #运行容器的副本数，修改这里可以快速修改分布式节点数量
  selector:
    matchLabels:
      app: ci-cd-demo
  template:
    metadata:
      labels:
        app: ci-cd-demo
    spec:
      containers: #docker容器的配置
        - name: APP_NAME
          image: ProjectImage
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: JAVA_OPTS
              value: -Xms256m -Xmx256m
      imagePullSecrets:
        - name: harborsecret
