spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    console: debug
  config: classpath:LOG-CONF/logback-dev.xml
mybatis-plus:
  configuration:
    # 控制台日志打印配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
rc:
  log:
    web:
      enabled: true