spring:
  main:
    lazy-initialization: true # 开启懒加载，加快速度
    banner-mode: off # 单元测试，禁用 Banner

--- #################### 数据库相关配置 ####################

spring:
  datasource:
    dynamic: # 多数据源配置
      druid: # Druid 【连接池】相关的全局配置
        async-init: true # 单元测试，异步初始化 Druid 连接池，提升启动速度
        initial-size: 1 # 单元测试，配置为 1，提升启动速度
      primary: master
      datasource:
        master:
          name: rc-cloud-system
          url: jdbc:h2:mem:testdb;MODE=MYSQL;DATABASE_TO_UPPER=false;NON_KEYWORDS=value; # MODE 使用 MySQL 模式；DATABASE_TO_UPPER 配置表和字段使用小写
          driver-class-name: org.h2.Driver
          username: 'sa'
          password: ''
  sql:
    init:
      schema-locations: classpath:/sql/create_tables.sql
  quartz:
    auto-startup: false # 关闭

  # Redis 配置。Redisson 默认的配置足够使用，一般不需要进行调优
  redis:
    host: 127.0.0.1 # 地址
    port: 16379 # 端口（单元测试，使用 16379 端口）
    database: 0 # 数据库索引


mybatis:
  lazy-initialization: true # 单元测试，设置 MyBatis Mapper 延迟加载，加速每个单元测试

--- #################### 定时任务相关配置 ####################

--- #################### 配置中心相关配置 ####################

--- #################### 服务保障相关配置 ####################

# Lock4j 配置项（单元测试，禁用 Lock4j）

--- #################### RC相关配置 ####################

# RC配置项，设置当前项目所有自定义的配置
rc:
  info:
    base-package: com.rc.cloud.app.system.biz.mapper
  captcha:
    timeout: 5m
    width: 160
    height: 60
    enable: true
