server:
  port: 8020

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: rc-ops-gateway
  # 激活环境配置
  profiles:
    active: dev
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
    gateway:
      globalcors:
        default-filters:
          - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Headers Access-Control-Allow-Credentials,RETAIN_UNIQUE
      locator:
        enabled: true
      routes:
        # auth 模块
        - id: rc-ops-auth
          uri: lb://rc-ops-auth
          predicates:
            - Path=/auth/**
          filters:
            # 验证码处理
            - ValidateCodeGatewayFilter
            # 前端密码解密
            - PasswordDecoderFilter
        # system 模块
        - id: rc-app-system-biz
          uri: lb://rc-app-system-biz
          predicates:
            - Path=/admin/**
          filters:
            # 限流配置
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 200
        # 经销商 模块
        - id: rc-app-distributor-biz
          uri: lb://rc-app-distributor-biz
          predicates:
            - Path=/distributor/**
        # base-config 模块
        - id: rc-base-config
          uri: lb://rc-base-config
          predicates:
            - Path=/base-config/**
        # 代码生成模块
#        - id: rc-codegen
#          uri: lb://rc-codegen
#          predicates:
#            - Path=/gen/**
        # 固定路由转发配置 无修改
        - id: openapi
          uri: lb://rc-ops-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/$\{path}/v3/api-docs
gateway:
  encode-key: 'thanks,pig4cloud'
  ignore-clients: # 不校验验证码的客户端
    - test
    - client

# swagger 配置
swagger:
  enabled: true
  title: RC Swagger API
  gateway: http://127.0.0.1:9999
  token-url: ${swagger.gateway}/auth/oauth2/token
  scope: server
  services:
    rc-app-system-biz: admin
    rc-codegen: gen